// Code generated by DevUp technologies, 11/12/2023 17:23:46
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using CommonInterfaces;


namespace InventoryApiTests.ObjectFactories
{    
	public class ProductObjectFactory
    {
        public static ProductDTO CreateSingle(long postFix)
        {
            return new ProductDTO()
            {
				Name = postFix.ToString(),
				CategoryId = DateTime.Now.Millisecond,
				Status = DateTime.Now.Millisecond,
				NetPrice = postFix,
				SalesPrice = postFix,
				StockQuantity = postFix,
				ProductionDate = DateTime.Now,

            };
        }

        public static List<ProductDTO> CreateMany(long count)
        {
            List<ProductDTO> auditList = new List<ProductDTO>();
            for (int i = 0; i < count; i++)
            {
				long itemNumber = long.Parse(DateTime.Now.ToString("yMMddhhmmssfff"))+ count;
                auditList.Add(CreateSingle(itemNumber));
            }

            return auditList;
        }
    }
}


