// Code generated by DevUp technologies, 11/12/2023 17:23:45
using Microsoft.EntityFrameworkCore;

namespace InventoryDAL
{
    public class InventoryContext : DbContext
    {
        public InventoryContext(DbContextOptions<InventoryContext> options) : base(options)
        {
        }


		public DbSet<Product> Product { get; set; }


    }
}

