// Code generated by DevUp technologies, 11/12/2023 17:23:45
using Microsoft.EntityFrameworkCore;

namespace InventoryDAL.Container
{
    public class IOCContainer
    {
        private static IOCContainer _instance;
        private string ConnectionString { get; set; }
        public static void Initialize(string connectionString)
        {
            IOCContainer.Instance.ConnectionString = connectionString;
        }
        public static IOCContainer Instance
        {
            get
            {
                if (_instance == null)
                    _instance = new IOCContainer();

                return _instance;
            }
        }

        public DbContextOptionsBuilder<InventoryContext> OptionsBuilder
        {
            get
            {
                var optionsBuilder = new DbContextOptionsBuilder<InventoryContext>();
                return optionsBuilder.UseSqlServer(ConnectionString);
            }
        }

        public InventoryContext Context
        {
            get
            {
                return new InventoryContext(IOCContainer.Instance.OptionsBuilder.Options);
            }
        }
		public ProductRepository ProductRepository
		{
			get
			{
				return new ProductRepository(Context);
			}
		}


    }
}

