// Code generated by DevUp technologies, 11/12/2023 17:23:45
using AutoMapper;
using CommonInterfaces;
using InventoryDAL;

namespace CommonServices.Mappers
{
    public class EFToDTOProfile : Profile
    {
        public EFToDTOProfile()
        {
			
			CreateMap<Product, ProductDTO>();
			CreateMap<ProductFilter, ProductFilterDTO>();

 
        }
    }
}

