// Code generated by DevUp technologies, 11/12/2023 17:23:46
using CommonInterfaces;
using CommonServices;

namespace InventoryWApi.Extensions
{
    public static class ServiceRegistration
    {
        public static void AddServices(this IServiceCollection services)
        {
			services.AddScoped<IProductService, ProductService>();


        }
    }
}

